spring:
  datasource:
    url: jdbc:sqlserver://piyush-server.database.windows.net:1433;database=springdb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: piyush
    password: Password###01
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect    
server:
  port: 8080